### ISSUE TITLE
data-element is unknown

### ISSUE THREAD

**Issue by yishay-at-bay** [fullstorydev/fullstory-babel-plugin-annotate-react#165]
**Your Questions**
I'm not sure if it is a bug or maybe I'm doing something wrong, but when I use the plugin with React I get data-element="unknown" in all elements

**Context**
I'm using it on CRA

<img width="529" alt="element" src="https://github.com/fullstorydev/fullstory-babel-plugin-annotate-react/assets/95177000/23e8ec93-44c5-4fef-bde9-d7e5e14ddf7a">

**Comment by sabrina-li** [comment]
Hi @yishay-at-bay thank you for creating an issue with us. 
Would you please provide the following:
- React and CRA version
- The code snippet 
 - If possible a small git repository that we could use to try and replicate the behavior

Thank you!

**Comment by RyanCommits** [comment]
Closing stale issue without response. Please open a new issue with the requested information.
