### ISSUE TITLE
README inaccuracy

### ISSUE THREAD

**Issue by van-fs** [fullstorydev/fullstory-babel-plugin-annotate-react#181]
**Describe the bug**
The readme states, "For React on the web the attributes are data-component, data-element, and data-source-file. For React Native the attributes are dataComponent, dataElement, and dataSourceFile."

**To Reproduce**
N/A

**Expected behavior**
From looking at selectors in a native mobile org, `data-` attribute selectors definitely index for Mobile Apps platform dependent criteria.  I'm not seeing any for `dataComponent` though.  Kevin and Prashanth both said that's a doc bug FWIW.  Can we remove the incorrect distinction between web and mobile?  My understanding is that its `data-*` regardless of platform but could use someone more knowledge to clarify.

**Actual behavior**
N/A

**Node env (please complete the following information):**
N/A

**Additional comments**

**Logs**
N/A

**Comment by JoshMiers-FS** [comment]
It depends on where you look or what it is actually referring to. In order to get React Native to compile, internally the attributes actually are camel case. However, that is later changed to kebab-case when it hits our backend (I forget where).

**Comment by van-fs** [comment]
@JoshMiers-FS Perhaps we append the text in bold to the paragraph. WDYT?

For React on the web the attributes are `data-component`, `data-element`, and `data-source-file`. For React Native the attributes are `dataComponent`, `dataElement`, and `dataSourceFile`. **Note that for both React web and Native, these attributes will appear as kebab-case in the Fullstory application due to backend processing. End users of Fullstory should create search filters (i.e. segments, metrics, etc) using kebab-case.**
