### ISSUE TITLE
Doc Improvements

### ISSUE THREAD

**Issue by amcdnl** [fullstorydev/fullstory-babel-plugin-annotate-react#22]
Few suggestions for improving the docs:

- You never show how to install it - for example I had to look in the package.json to find out exactly what the package name was
- The docs don't really show how to configure it for basic - it shows the react native portion which i just copied and realized after the fact i needed to remove that

**Comment by patrick-fs** [comment]
Thanks Austin,

Good catch. We'll revisit the docs.

**Comment by ChaosDeSelva** [comment]
Vite docs?
