### ISSUE TITLE
Some Components Not Annotated

### ISSUE THREAD

**Issue by amcdnl** [fullstorydev/fullstory-babel-plugin-annotate-react#24]
In my project, some of the components are not getting annotated. If you see this snapshot:

![image](https://user-images.githubusercontent.com/227909/102408678-f06c5d80-3fbb-11eb-8dd6-09e40fe764c0.png)

The div element with class name is `Nav_container` is a component.  I'm wondering if that is because the dom structure has a fragment rather than a DOM element:

```jsx
const Nav = () => (
  <Fragment>
     <div className="Nav_container" />
  </Fragment>
);
```

I understand the issue is you need something to attach to and since a fragment isn't a real element you have nothing to attach to but...I'm thinking you could solve this in a few different ways:

- You could attach the attributes to the children of the fragment
- You could attach the attributes to ALL children until you hit another component and so on...

**Comment by patrick-fs** [comment]
Another great catch. Thanks for surfacing this and for the suggested fixes.
